#!/usr/bin/env node
// FictionPad local server: serves the compiled single-file app
// (fictionpad.compiled.html — auto-built in the background on first run when
// missing; the esm.sh dev build is the fallback), proxies LLM API calls
// (mikupad-style /proxy/*), and optionally stores sessions in SQLite.
// Zero dependencies — requires Node.js >= 22.13 (node:sqlite, unflagged).
//
// Usage:
//   node server.mjs [port]          (default port 8788)
//   open http://localhost:8788
// Then set the in-app endpoint to your real LLM server as usual — but route it
// through the proxy:  http://localhost:8788/proxy/<your-real-endpoint>
// Example:  http://localhost:8788/proxy/http://127.0.0.1:8080
//           http://localhost:8788/proxy/https://api.openai.com
// (The app normalizes and appends /v1/chat/completions etc. — everything after
// /proxy/ is forwarded verbatim as the target URL.)
//
// Env:
//   FICTIONPAD_DB       SQLite path (default: fictionpad.db next to server.mjs)
//   FICTIONPAD_TOKEN    storage routes require Authorization: Bearer <token>
//   FICTIONPAD_AUTH     user:password — whole-server HTTP Basic auth (except
//                       /health). The proxy never forwards these creds upstream;
//                       the app sends its LLM key as X-Real-Authorization instead.
//   FICTIONPAD_PROXY_ALLOW  comma-separated target host allowlist for /proxy
//                       (e.g. "proxy.example.com,10.0.0.6"). Default: any host
//                       when auth is configured; loopback-only with no auth
//                       (see the policy below).
// Proxy access policy:
//   - FICTIONPAD_AUTH set   → /proxy is behind Basic like everything else.
//   - only FICTIONPAD_TOKEN → /proxy requires the same Bearer token.
//   - neither set           → /proxy only forwards to loopback targets
//                             (localhost/127.0.0.1/[::1]), so an exposed
//                             unauthenticated server is not an open relay.
// 401s generated by THIS server carry `X-FictionPad-Auth: required` so the app
// can tell them apart from upstream (proxied) 401s, which pass through untagged.
//
//   FICTIONPAD_CHECKPOINT_MS  interval for PRAGMA wal_checkpoint(TRUNCATE)
//                       in ms (default 60000) — keeps the on-disk .db a
//                       recent complete snapshot even without a shutdown.
//   GET /backup       checkpoints the WAL, snapshots the .db to a temp copy,
//                     then streams the copy as an attachment (same auth as the
//                     storage routes).
//   POST /gc-images   server-side image GC: deletes Images rows no stored
//                     entity references (same auth + Origin guard as the
//                     storage routes). A per-client sweep would delete rows
//                     other clients sharing this server still cite.
//   FICTIONPAD_UPSTREAM_TIMEOUT_MS  total-duration cap per /proxy upstream
//                       call in ms (default 300000 — LLM streams can be long).
//   FICTIONPAD_AUTOBUILD=0  disable the background build of
//                       fictionpad.compiled.html when it's missing (default:
//                       build once per process at startup, never blocking).
// CORS: Access-Control-Allow-Origin and the preflight answer are emitted
//   only when the request's Origin header is absent (same-origin/curl) or
//   exactly "null" (the file:// build — the only reason CORS exists). Any
//   other Origin is still served but gets no ACAO header, so browsers refuse
//   to let that page read the response. Writes are guarded separately: the
//   storage and /proxy routes reject any request carrying a foreign Origin —
//   simple cross-site POSTs bypass ACAO, so a no-auth deployment would
//   otherwise let any website overwrite a visitor's data via their browser.
// Wire compression: JSON responses over 1 KB are gzipped when the request's
//   Accept-Encoding allows it, and storage-route request bodies may carry
//   Content-Encoding: gzip (the body cap bounds BOTH the compressed bytes on
//   the wire and the decompressed payload). The ~1 MB app HTML is served
//   gzipped from a cache keyed on file path + mtime (the per-request re-read
//   stays). /proxy and /backup traffic is never re-encoded. /version
//   advertises the capability (gzip: true).
// Shutdown: SIGINT/SIGTERM close the db — closing the last WAL connection
//   checkpoints it and removes the -wal/-shm sidecars — then exit 0.

import http from 'node:http';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { copyFile, readFile, unlink } from 'node:fs/promises';
import { existsSync, statSync, createReadStream } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { gzipSync, gunzipSync } from 'node:zlib';

// Port 0 = let the OS pick (tests) — the startup log prints the bound port.
const PORT = process.argv[2] === '0' ? 0 : Number(process.argv[2]) || 8788;
const ROOT = dirname(fileURLToPath(import.meta.url));
const DB_PATH = process.env.FICTIONPAD_DB || join(ROOT, 'fictionpad.db');
const TOKEN = process.env.FICTIONPAD_TOKEN || null; // when set, storage routes need Bearer auth
// Request-body cap for storage + proxy routes. Chats carry images as data
// URLs (avatars incl. the full-res avatarFull, generated-image takes), so a
// busy chat JSON easily clears 8 MB — 64 MB default, env-overridable.
const MAX_BODY = (Number(process.env.FICTIONPAD_MAX_BODY_MB) || 64) * 1024 * 1024;
// Total-duration cap per upstream /proxy call (streams included) — a hung
// endpoint must not pin a socket forever. 5 min default, env-overridable.
const UPSTREAM_TIMEOUT_MS = Number(process.env.FICTIONPAD_UPSTREAM_TIMEOUT_MS) || 5 * 60_000;

// Whole-server HTTP Basic auth (LAN exposure): FICTIONPAD_AUTH=user:password.
// Everything except /health requires it; checked before the Bearer token.
let BASIC_USER = null, BASIC_HEADER = null;
if (process.env.FICTIONPAD_AUTH) {
  const i = process.env.FICTIONPAD_AUTH.indexOf(':');
  if (i > 0) {
    BASIC_USER = process.env.FICTIONPAD_AUTH.slice(0, i);
    BASIC_HEADER = `Basic ${Buffer.from(process.env.FICTIONPAD_AUTH, 'utf8').toString('base64')}`;
  } else {
    console.warn('FICTIONPAD_AUTH is malformed (expected user:password) — ignoring it.');
  }
}
// Constant-time credential comparison (length guard first — timingSafeEqual
// throws on length mismatch).
const safeEqual = (a, b) => {
  const ba = Buffer.from(String(a), 'utf8'), bb = Buffer.from(String(b), 'utf8');
  return ba.length === bb.length && crypto.timingSafeEqual(ba, bb);
};
const bearerOk = (req) => !!TOKEN && safeEqual(req.headers.authorization ?? '', `Bearer ${TOKEN}`);
const basicOk = (req) => !!BASIC_HEADER && safeEqual(req.headers.authorization ?? '', BASIC_HEADER);
// One credential check for every gated route: Basic (when configured) OR
// Bearer (when configured) — a request carries only one Authorization header,
// and app subrequests legitimately use Bearer while the browser uses Basic.
// With neither configured the server is open (local dev; see the startup warning).
const credsOk = (req) => (!BASIC_HEADER && !TOKEN) || basicOk(req) || bearerOk(req);
const isBearer = (req) => /^Bearer /i.test(req.headers.authorization ?? '');
const basicChallenge = (res, req) => {
  // A request that already presented Bearer creds comes from an API client
  // (never a bare browser navigation) — answering with WWW-Authenticate would
  // make Safari/Chrome pop the native password sheet on every failed fetch.
  // X-FictionPad-Auth tags this as OUR 401 (vs. an upstream passthrough).
  const headers = { 'Content-Type': 'application/json', 'X-FictionPad-Auth': 'required' };
  if (!isBearer(req)) headers['WWW-Authenticate'] = 'Basic realm="fictionpad"';
  res.writeHead(401, headers);
  res.end(JSON.stringify({ error: 'unauthorized' }));
};

// ---- server-side storage (mikupad-style): one kv table, gzip-compressed JSON ----
const KNOWN_STORES = new Set(['Scenarios', 'Personas', 'Chats', 'Meta', 'Characters', 'Images']);
let db;
try {
  db = new DatabaseSync(DB_PATH);
  db.exec('PRAGMA journal_mode=WAL;');
  db.exec('PRAGMA busy_timeout=5000;');
  db.exec('CREATE TABLE IF NOT EXISTS kv (store TEXT, key TEXT, data BLOB, PRIMARY KEY (store, key))');
  // Optimistic concurrency: every row carries a revision counter, bumped on
  // each write. Clients send their last-seen rev as baseRev on /save and a
  // mismatch is refused with 409 instead of silently clobbering a newer
  // write from another device. Pre-rev databases migrate in place (existing
  // rows start at rev 0, which any post-upgrade client boot reads back).
  if (!db.prepare("SELECT 1 FROM pragma_table_info('kv') WHERE name = 'rev'").get())
    db.exec('ALTER TABLE kv ADD COLUMN rev INTEGER NOT NULL DEFAULT 0');
} catch (err) {
  console.error(`FictionPad: cannot open or initialize the SQLite database at ${DB_PATH}`);
  console.error(`  (${err?.message || err})`);
  console.error(`  Delete or restore ${DB_PATH}, then restart the server.`);
  process.exit(1);
}

// ---- imgref rehydration for pre-v4.11 clients ----
// New clients persist image payloads as separate Images rows, leaving
// `imgref:<id>` sentinels inside entities, and rehydrate client-side (they
// pass `refs: true` on /load and /all, which also keeps their boot payloads
// thin). Clients that predate the feature would render broken images from
// the sentinels, so their reads are rehydrated here instead. The sentinel
// format must stay in sync with the app's src/30-core.js.
const IMGREF_RE = /^imgref:([0-9a-f]{16}(?:-[0-9]+)?)$/;
function rehydrateRefs(value, loadImages) {
  if (typeof value === 'string') {
    if (!value.startsWith('imgref:')) return value;
    const m = IMGREF_RE.exec(value);
    if (!m) return value;
    const hit = loadImages().get(m[1]);
    return hit !== undefined ? hit : value;
  }
  if (Array.isArray(value)) { for (let i = 0; i < value.length; i++) value[i] = rehydrateRefs(value[i], loadImages); return value; }
  if (value && typeof value === 'object') { for (const k of Object.keys(value)) value[k] = rehydrateRefs(value[k], loadImages); return value; }
  return value;
}
// Per-request lazy Images map — built at most once, and only when a blob
// actually contains the sentinel prefix (checked on the raw JSON text).
function imagesLoader() {
  let m = null;
  return () => {
    if (!m) {
      m = new Map();
      for (const row of db.prepare('SELECT key, data FROM kv WHERE store = ?').all('Images')) {
        try { m.set(row.key, JSON.parse(gunzipSync(row.data).toString('utf8'))); } catch {}
      }
    }
    return m;
  };
}
function maybeRehydrate(text, refs) {
  const data = JSON.parse(text);
  if (refs === true || !text.includes('imgref:')) return data;
  return rehydrateRefs(data, imagesLoader());
}

// ---- WAL durability ----
// WAL mode keeps recent writes in fictionpad.db-wal until a checkpoint runs —
// copying just the .db (e.g. into a deploy) would silently lose them. Two
// guards: a periodic TRUNCATE checkpoint so the on-disk .db is always a
// recent complete snapshot, and a clean db.close() on shutdown — closing the
// last WAL connection checkpoints and removes the -wal/-shm sidecars.
const CHECKPOINT_MS = Number(process.env.FICTIONPAD_CHECKPOINT_MS) || 60_000;
const checkpointTimer = setInterval(() => {
  try { db.exec('PRAGMA wal_checkpoint(TRUNCATE);'); }
  catch (err) { console.warn(`WAL checkpoint failed: ${err?.message || err}`); }
}, CHECKPOINT_MS);
checkpointTimer.unref(); // housekeeping must never hold the process open
let shuttingDown = false;
const shutdown = (sig) => {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log(`FictionPad: ${sig} received — checkpointing and closing the database.`);
  clearInterval(checkpointTimer);
  try { db.close(); } catch { /* already closed */ }
  process.exit(0);
};
process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

// CORS exists solely for the file:// build, whose Origin header is the
// literal string "null". Same-origin pages and curl send no Origin and need
// nothing. Any OTHER Origin is served normally but gets no
// Access-Control-Allow-Origin header — the browser then refuses to let that
// page READ the response.
const acaoFor = (req) => {
  const origin = req.headers.origin;
  return (origin === undefined || origin === 'null')
    ? { 'Access-Control-Allow-Origin': '*' }
    : {};
};
// But ACAO only gates reading: browsers can still SEND simple cross-site
// requests (a form POST is CORS-safelisted), and Origin is a forbidden header
// a web page can neither forge nor omit. So the mutating routes (storage +
// /proxy) reject any request carrying a foreign Origin outright — otherwise
// any website could overwrite kv rows (incl. Meta/app.settings, which the app
// adopts at boot) on a no-auth deployment via a visitor's browser. Absent
// (curl, apps, same-origin navigations), "null" (file://), or this server's
// own Host all pass.
const originOk = (req) => {
  const o = req.headers.origin;
  if (o === undefined || o === 'null') return true;
  try { return new URL(o).host === req.headers.host; } catch { return false; }
};
// Token-level Accept-Encoding check — a substring test would take "xgzip".
const acceptsGzip = (req) =>
  (req.headers['accept-encoding'] ?? '').split(',')
    .some((t) => t.trim().toLowerCase().split(';')[0] === 'gzip');
const sendJson = (req, res, status, obj) => {
  const headers = { 'Content-Type': 'application/json', ...acaoFor(req) };
  // Tag OUR auth failures so the app can distinguish them from upstream 401s
  // that pass through the proxy untagged.
  if (status === 401) headers['X-FictionPad-Auth'] = 'required';
  const body = Buffer.from(JSON.stringify(obj), 'utf8');
  // Gzip only pays off past a trivial size — /all boot payloads carry whole
  // entities and compress ~10x, while errors and {ok:true} replies would
  // gain nothing. /proxy and /backup never go through here: their traffic
  // (streams, db snapshots) is passed through untouched.
  if (body.length > 1024 && acceptsGzip(req)) {
    headers['Content-Encoding'] = 'gzip';
    res.writeHead(status, headers);
    return res.end(gzipSync(body));
  }
  res.writeHead(status, headers);
  res.end(body);
};
const readJsonBody = async (req) => {
  // Storage bodies may arrive gzipped (the app compresses big chat saves).
  // An encoding we don't speak is refused outright — silently misreading it
  // would store garbage.
  const enc = (req.headers['content-encoding'] ?? 'identity').trim().toLowerCase();
  if (enc !== 'identity' && enc !== 'gzip') {
    const err = new Error('unsupported content-encoding');
    err.status = 415;
    throw err;
  }
  const chunks = [];
  let size = 0;
  for await (const c of req) {
    size += c.length;
    if (size > MAX_BODY) {
      const err = new Error('body too large');
      err.status = 413;
      throw err;
    }
    chunks.push(c);
  }
  if (!chunks.length) return {};
  let buf = Buffer.concat(chunks);
  if (enc === 'gzip') {
    buf = gunzipSync(buf); // a bad gzip stream throws → caller's 400
    // The cap above only bounded the compressed bytes on the wire — a highly
    // compressible payload must clear the same cap inflated (zip-bomb guard).
    if (buf.length > MAX_BODY) {
      const err = new Error('body too large');
      err.status = 413;
      throw err;
    }
  }
  return JSON.parse(buf.toString('utf8'));
};

const HOP_BY_HOP = new Set([
  'host', 'connection', 'keep-alive', 'transfer-encoding', 'te',
  'trailer', 'upgrade', 'proxy-authorization', 'proxy-authenticate',
]);

// /proxy target policy (see header comment). An allowlist always wins; an
// unauthenticated server is limited to loopback targets so it cannot be
// abused as an open relay.
const PROXY_ALLOW = (process.env.FICTIONPAD_PROXY_ALLOW ?? '')
  .split(',').map(s => s.trim().toLowerCase()).filter(Boolean);
const LOOPBACK_HOSTS = new Set(['localhost', '127.0.0.1', '::1', '[::1]']);
function proxyTargetAllowed(target) {
  let host;
  try { host = new URL(target).hostname.toLowerCase(); }
  catch { return { ok: false, reason: 'unparseable proxy target' }; }
  if (PROXY_ALLOW.length) {
    return PROXY_ALLOW.includes(host)
      ? { ok: true }
      : { ok: false, reason: `proxy target host "${host}" refused: it is not in the FICTIONPAD_PROXY_ALLOW ` +
          `allowlist (currently: ${PROXY_ALLOW.join(', ')}) — add it there, or unset FICTIONPAD_PROXY_ALLOW` +
          (BASIC_HEADER || TOKEN ? ' (with auth configured and no allowlist, any host is allowed)' : '') };
  }
  if (!BASIC_HEADER && !TOKEN && !LOOPBACK_HOSTS.has(host)) {
    return { ok: false, reason: `proxy target host "${host}" refused: FICTIONPAD_PROXY_ALLOW is not set and the ` +
      `server has no auth (FICTIONPAD_AUTH/FICTIONPAD_TOKEN), so /proxy only forwards to loopback targets ` +
      `(open-relay guard) — set FICTIONPAD_PROXY_ALLOW=${host} to allow it, or configure auth` };
  }
  return { ok: true };
}

// Serve the compiled (vendored, offline-capable) build when present — that's
// the distribution artifact; the readable source is the fallback (dev build,
// loads its JS deps from esm.sh at runtime). Resolved per request so a
// rebuild is picked up without a server restart.
const appFile = () => existsSync(join(ROOT, 'fictionpad.compiled.html'))
  ? 'fictionpad.compiled.html'
  : 'fictionpad.html';

// The app HTML is ~1 MB and re-read from disk per request by design (a
// rebuild is picked up without a restart) — compressing it fresh each time
// would be the expensive part, so the gzipped buffer is cached keyed on the
// file path + mtimeMs: a rebuild changes the mtime and invalidates the entry.
let htmlGzipCache = { key: null, buf: null };

// Fresh clones have no compiled artifact (it's gitignored — the release asset
// is the real distribution), so without this a first-time `node server.mjs`
// would serve the esm.sh dev build: a blank page anywhere the CDN is
// unreachable. Build the self-contained artifact in the background at
// startup — appFile() resolves per request, so the compiled build takes over
// the moment it lands, no restart. A failed build (offline, no vendor.mjs
// alongside) just keeps the fallback serving, with a warning. Once per
// process; FICTIONPAD_AUTOBUILD=0 opts out.
let autobuildTried = false;
function autobuildCompiled() {
  if (autobuildTried || process.env.FICTIONPAD_AUTOBUILD === '0') return;
  autobuildTried = true;
  if (existsSync(join(ROOT, 'fictionpad.compiled.html'))) return;
  if (!existsSync(join(ROOT, 'vendor.mjs'))) return; // artifact-only deploy — nothing to build with
  console.log('FictionPad: fictionpad.compiled.html missing — building it in the background ' +
    '(first run fetches the pinned deps from esm.sh once)…');
  const child = spawn(process.execPath, [join(ROOT, 'vendor.mjs')], { cwd: ROOT, stdio: 'inherit' });
  child.on('error', (err) =>
    console.warn(`FictionPad: could not run vendor.mjs (${err?.message || err}) — ` +
      'serving the esm.sh dev build, which needs internet access.'));
  child.on('exit', (code) => {
    if (code === 0 && existsSync(join(ROOT, 'fictionpad.compiled.html')))
      console.log('FictionPad: built fictionpad.compiled.html — now serving the self-contained build (no restart needed).');
    else
      console.warn('FictionPad: auto-build failed — serving fictionpad.html, which loads React/htm/marked ' +
        'from esm.sh on every page open. Run `node vendor.mjs` once with internet access, or use the release asset.');
  });
}

async function handleRequest(req, res) {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);

  // CORS preflight — answered with full CORS headers only for the origins we
  // allow (see acaoFor); any other Origin gets a bare 204, which the browser
  // treats as a failed preflight.
  if (req.method === 'OPTIONS') {
    const acao = acaoFor(req);
    res.writeHead(204, 'Access-Control-Allow-Origin' in acao ? {
      ...acao,
      'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Real-Authorization',
      'Access-Control-Max-Age': '86400',
    } : {});
    return res.end();
  }

  if (url.pathname === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ ok: true }));
  }

  // Whole-server Basic auth (when FICTIONPAD_AUTH is set) — before everything
  // else. A valid Bearer token also passes (app subrequests use Bearer while
  // the browser uses Basic). /health stays open.
  if (BASIC_HEADER && !credsOk(req)) return basicChallenge(res, req);

  if (url.pathname === '/' || url.pathname === '/fictionpad.html') {
    const file = appFile();
    try {
      const path = join(ROOT, file);
      const html = await readFile(path);
      const headers = { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-cache' };
      if (html.length > 1024 && acceptsGzip(req)) {
        const cacheKey = `${file}:${statSync(path).mtimeMs}`;
        if (htmlGzipCache.key !== cacheKey) htmlGzipCache = { key: cacheKey, buf: gzipSync(html) };
        headers['Content-Encoding'] = 'gzip';
        res.writeHead(200, headers);
        return res.end(htmlGzipCache.buf);
      }
      res.writeHead(200, headers);
      return res.end(html);
    } catch {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      return res.end(`${file} not found next to server.mjs`);
    }
  }

  // ---- storage protocol ----
  // Gated by either configured credential (Basic or Bearer); open when neither
  // is set (local dev default — see the startup warning).
  if (url.pathname === '/version' && req.method === 'GET') {
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    return sendJson(req, res, 200, { version: 1, storage: true, images: true, gc: true, rev: true, gzip: true });
  }

  // Full-db backup: checkpoint the WAL, then snapshot the .db to a temp copy
  // and stream THAT. Streaming the live file would race: a mid-stream
  // auto-checkpoint or a second concurrent /backup's TRUNCATE can change the
  // file size under the open read stream, corrupting the download against its
  // stat'd Content-Length. The copy is stat'd after landing and unlinked when
  // the response closes (completion, client disconnect, or error alike).
  if (url.pathname === '/backup') {
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    if (req.method !== 'GET') return sendJson(req, res, 405, { error: 'GET required' });
    const tmpFile = join(tmpdir(), `fictionpad-backup-${process.pid}-${crypto.randomUUID()}.db`);
    try {
      db.exec('PRAGMA wal_checkpoint(TRUNCATE);');
      await copyFile(DB_PATH, tmpFile);
      const { size } = statSync(tmpFile);
      const stamp = new Date().toISOString().replace(/[:.]/g, '-');
      res.writeHead(200, {
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': `attachment; filename="fictionpad-backup-${stamp}.db"`,
        'Content-Length': size,
        ...acaoFor(req),
      });
      res.on('close', () => { unlink(tmpFile).catch(() => {}); });
      createReadStream(tmpFile).pipe(res);
    } catch (err) {
      await unlink(tmpFile).catch(() => {});
      return sendJson(req, res, 500, { error: `backup failed: ${err?.message || err}` });
    }
    return;
  }

  // Server-side image GC: entities keep images out-of-band as imgref:<id>
  // sentinels, the payloads as Images rows. With server storage shared between
  // clients, a per-client sweep (scanning only its own cache) would delete
  // rows another client's entities still reference — so the sweep runs here,
  // over EVERY stored entity. Meta is app/device settings, not entity state,
  // and is excluded like the Images rows themselves.
  if (url.pathname === '/gc-images') {
    if (!originOk(req)) return sendJson(req, res, 403, { error: 'cross-site writes are not accepted (foreign Origin)' });
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    if (req.method !== 'POST') return sendJson(req, res, 405, { error: 'POST required' });
    const refs = new Set();
    const collect = (value) => {
      if (typeof value === 'string') {
        const m = value.startsWith('imgref:') && IMGREF_RE.exec(value);
        if (m) refs.add(m[1]);
        return;
      }
      if (Array.isArray(value)) { for (const v of value) collect(v); return; }
      if (value && typeof value === 'object') { for (const k of Object.keys(value)) collect(value[k]); }
    };
    try {
      for (const row of db.prepare("SELECT store, key, data FROM kv WHERE store NOT IN ('Images', 'Meta')").all()) {
        // Safe-fail, not skip: a row that fails to decode MIGHT reference
        // images, so skipping it could orphan-delete live rows. Abort the
        // whole sweep with a 500 instead — nothing is deleted.
        try { collect(JSON.parse(gunzipSync(row.data).toString('utf8'))); }
        catch (err) { throw new Error(`undecodable kv row ${row.store}/${row.key}: ${err?.message || err}`); }
      }
    } catch (err) {
      console.warn(`gc-images aborted: ${err?.message || err}`);
      return sendJson(req, res, 500, { error: `gc-images aborted: ${err?.message || err}` });
    }
    let deleted = 0;
    const del = db.prepare('DELETE FROM kv WHERE store = ? AND key = ?');
    for (const row of db.prepare('SELECT key FROM kv WHERE store = ?').all('Images')) {
      if (!refs.has(row.key)) { del.run('Images', row.key); deleted++; }
    }
    return sendJson(req, res, 200, { deleted });
  }

  if (['/load', '/save', '/all', '/delete', '/list'].includes(url.pathname)) {
    if (!originOk(req)) return sendJson(req, res, 403, { error: 'cross-site writes are not accepted (foreign Origin)' });
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    if (req.method !== 'POST') return sendJson(req, res, 405, { error: 'POST required' });
    let body;
    try { body = await readJsonBody(req); }
    catch (err) {
      if (err?.status === 413) return sendJson(req, res, 413, { error: 'body too large' });
      if (err?.status === 415) return sendJson(req, res, 415, { error: 'unsupported content-encoding' });
      return sendJson(req, res, 400, { error: 'invalid JSON' });
    }
    const { store, key, data } = body ?? {};
    if (url.pathname !== '/list' && !KNOWN_STORES.has(store))
      return sendJson(req, res, 400, { error: `unknown store: ${store}` });
    switch (url.pathname) {
      case '/load': {
        const row = db.prepare('SELECT data, rev FROM kv WHERE store = ? AND key = ?').get(store, String(key));
        if (!row) return sendJson(req, res, 404, { error: 'not found' });
        try {
          return sendJson(req, res, 200, { data: maybeRehydrate(gunzipSync(row.data).toString('utf8'), body.refs), rev: row.rev });
        } catch (err) {
          console.warn(`corrupted kv row ${store}/${key}: ${err?.message || err}`);
          return sendJson(req, res, 500, { error: 'corrupted stored data' });
        }
      }
      case '/save': {
        if (key == null || String(key) === '') return sendJson(req, res, 400, { error: 'missing key' });
        if (data === undefined) return sendJson(req, res, 400, { error: 'missing data' });
        const blob = gzipSync(Buffer.from(JSON.stringify(data), 'utf8'));
        // Guarded write: baseRev is the rev the client's copy is based on
        // (0 = "must not exist yet"). A mismatch means another device wrote
        // in between — refuse with 409 instead of clobbering. No baseRev
        // (pre-rev client) = legacy blind upsert, rev still bumped.
        const baseRev = body.baseRev;
        if (baseRev == null) {
          db.prepare('INSERT INTO kv (store, key, data, rev) VALUES (?, ?, ?, 1) ' +
            'ON CONFLICT(store, key) DO UPDATE SET data = excluded.data, rev = kv.rev + 1')
            .run(store, String(key), blob);
          const { rev } = db.prepare('SELECT rev FROM kv WHERE store = ? AND key = ?').get(store, String(key));
          return sendJson(req, res, 200, { ok: true, rev });
        }
        if (!Number.isInteger(baseRev) || baseRev < 0)
          return sendJson(req, res, 400, { error: 'baseRev must be a non-negative integer' });
        db.exec('BEGIN IMMEDIATE');
        try {
          const row = db.prepare('SELECT rev FROM kv WHERE store = ? AND key = ?').get(store, String(key));
          const current = row?.rev ?? null;
          if (current === baseRev || (current === null && baseRev === 0)) {
            db.prepare('INSERT INTO kv (store, key, data, rev) VALUES (?, ?, ?, 1) ' +
              'ON CONFLICT(store, key) DO UPDATE SET data = excluded.data, rev = kv.rev + 1')
              .run(store, String(key), blob);
            db.exec('COMMIT');
            return sendJson(req, res, 200, { ok: true, rev: (current ?? 0) + 1 });
          }
          db.exec('ROLLBACK');
          // No data payload — the client /loads the winning version; keeps
          // 409s small even for image-heavy chats.
          return sendJson(req, res, 409, { error: 'conflict', rev: current });
        } catch (err) {
          try { db.exec('ROLLBACK'); } catch {}
          throw err;
        }
      }
      case '/all': {
        // Delta sync (multi-device boot): `known` maps key → the client's
        // last-seen rev. Only entries whose rev differs (new keys included —
        // they're absent from `known`) are decoded and sent; `revs` still
        // covers EVERY key in the store so the client can resync its full
        // rev map from it, and `deleted` lists the known keys that vanished
        // server-side since the client's snapshot. No `known` = the legacy
        // full dump with NO deleted field — its absence is how the client
        // detects an old server that ignored the hint.
        const known = (body.known && typeof body.known === 'object' && !Array.isArray(body.known))
          ? body.known : null;
        const entries = {}, revs = {};
        const loadImages = imagesLoader();
        for (const row of db.prepare('SELECT key, data, rev FROM kv WHERE store = ?').all(store)) {
          revs[row.key] = row.rev;
          if (known && known[row.key] === row.rev) continue; // unchanged since the client's snapshot
          try {
            const text = gunzipSync(row.data).toString('utf8');
            const data = JSON.parse(text);
            entries[row.key] = (body.refs === true || !text.includes('imgref:')) ? data : rehydrateRefs(data, loadImages);
          } catch (err) {
            // One bad row must not take down the whole store (the app calls
            // /all at boot) — skip it and keep serving the rest.
            console.warn(`skipping corrupted kv row ${store}/${row.key}: ${err?.message || err}`);
          }
        }
        const out = { entries, revs };
        if (known) out.deleted = Object.keys(known).filter((k) => !(k in revs));
        return sendJson(req, res, 200, out);
      }
      case '/delete': {
        // Guarded delete, mirroring the /save contract: baseRev is the rev
        // the client's copy is based on, and a mismatch means another device
        // wrote in between — refuse with 409 instead of deleting the newer
        // write. No baseRev (legacy client) = blind delete. A missing row
        // succeeds either way: there is nothing to clobber.
        const baseRev = body.baseRev;
        if (baseRev == null) {
          db.prepare('DELETE FROM kv WHERE store = ? AND key = ?').run(store, String(key));
          return sendJson(req, res, 200, { ok: true });
        }
        if (!Number.isInteger(baseRev) || baseRev < 0)
          return sendJson(req, res, 400, { error: 'baseRev must be a non-negative integer' });
        db.exec('BEGIN IMMEDIATE');
        try {
          const row = db.prepare('SELECT rev FROM kv WHERE store = ? AND key = ?').get(store, String(key));
          if (!row) {
            db.exec('COMMIT');
            return sendJson(req, res, 200, { ok: true });
          }
          if (row.rev === baseRev) {
            db.prepare('DELETE FROM kv WHERE store = ? AND key = ?').run(store, String(key));
            db.exec('COMMIT');
            return sendJson(req, res, 200, { ok: true });
          }
          db.exec('ROLLBACK');
          return sendJson(req, res, 409, { error: 'conflict', rev: row.rev });
        } catch (err) {
          try { db.exec('ROLLBACK'); } catch {}
          throw err;
        }
      }
      case '/list': {
        const stores = {};
        for (const row of db.prepare('SELECT store, COUNT(*) AS n FROM kv GROUP BY store').all())
          stores[row.store] = row.n;
        const out = { stores };
        // revs: true — cheap per-key revision map (the client's focus sync
        // diffs against this instead of re-pulling every entity).
        if (body.revs === true) {
          out.revs = {};
          for (const row of db.prepare('SELECT store, key, rev FROM kv').all())
            (out.revs[row.store] ??= {})[row.key] = row.rev;
        }
        return sendJson(req, res, 200, out);
      }
    }
  }

  if (url.pathname.startsWith('/proxy/')) {
    // Gated by either configured credential, same as the storage routes; open
    // only when the server has no auth at all (and then loopback-only below).
    if (!originOk(req)) return sendJson(req, res, 403, { error: 'cross-site requests are not accepted (foreign Origin)' });
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    let target;
    try {
      target = decodeURIComponent(url.pathname.slice('/proxy/'.length)) + url.search;
    } catch {
      return sendJson(req, res, 400, { error: 'malformed proxy target (bad percent-encoding)' });
    }
    if (!/^https?:\/\//i.test(target)) {
      res.writeHead(400, { 'Content-Type': 'text/plain', ...acaoFor(req) });
      return res.end('proxy target must start with http:// or https://');
    }
    const verdict = proxyTargetAllowed(target);
    if (!verdict.ok) {
      res.writeHead(403, { 'Content-Type': 'text/plain', ...acaoFor(req) });
      return res.end(verdict.reason);
    }

    // Collect the request body (if any), capped at MAX_BODY.
    const chunks = [];
    let size = 0, tooBig = false;
    for await (const chunk of req) {
      size += chunk.length;
      if (size > MAX_BODY) { tooBig = true; break; }
      chunks.push(chunk);
    }
    if (tooBig) {
      req.destroy();
      return sendJson(req, res, 413, { error: 'body too large' });
    }
    const body = chunks.length ? Buffer.concat(chunks) : undefined;

    const headers = {};
    for (const [k, v] of Object.entries(req.headers)) {
      const lk = k.toLowerCase();
      if (HOP_BY_HOP.has(lk) || lk === 'cookie' || lk === 'x-real-authorization') continue;
      if (lk === 'authorization' && BASIC_HEADER && safeEqual(v, BASIC_HEADER)) continue; // never leak our own Basic creds upstream
      if (lk === 'authorization' && TOKEN && safeEqual(v, `Bearer ${TOKEN}`)) continue;   // ...nor our own Bearer token
      if (typeof v === 'string') headers[k] = v;
    }
    // The app sends the LLM key as X-Real-Authorization when routing through
    // this proxy; map it to the upstream Authorization header.
    const realAuth = req.headers['x-real-authorization'];
    if (typeof realAuth === 'string') headers['authorization'] = realAuth;

    // Propagate client disconnects to the upstream request; cap the upstream
    // call at UPSTREAM_TIMEOUT_MS so a hung endpoint can't pin a socket forever.
    const ac = new AbortController();
    res.on('close', () => ac.abort());
    const signal = AbortSignal.any([ac.signal, AbortSignal.timeout(UPSTREAM_TIMEOUT_MS)]);

    try {
      const upstream = await fetch(target, {
        method: req.method,
        headers,
        body,
        redirect: 'manual', // never follow redirects past the target policy — a 3xx passes through to the client
        signal,
      });

      const resHeaders = {
        ...acaoFor(req),
        'Content-Type': upstream.headers.get('content-type') || 'application/octet-stream',
        'Cache-Control': 'no-cache',
      };
      res.writeHead(upstream.status, resHeaders);

      // Stream the body back chunk-by-chunk (keeps SSE/token streaming live).
      if (!upstream.body) return res.end();
      const reader = upstream.body.getReader();
      const pump = async () => {
        try {
          for (;;) {
            const { done, value } = await reader.read();
            if (done) break;
            if (!res.write(value)) {
              await new Promise((resolve) => res.once('drain', resolve));
            }
          }
          res.end();
        } catch {
          res.destroy();
        }
      };
      pump();
    } catch (err) {
      if (err?.name === 'AbortError') return;
      res.writeHead(502, { 'Content-Type': 'text/plain', ...acaoFor(req) });
      res.end(`proxy error: ${err?.message || err}`);
    }
    return;
  }

  res.writeHead(404, { 'Content-Type': 'text/plain' });
  res.end('not found');
}

// The handler is async — an uncaught throw would kill the process. Last-line
// safety net: answer 500 and keep serving.
const server = http.createServer(async (req, res) => {
  try {
    await handleRequest(req, res);
  } catch (err) {
    console.error(`unhandled error on ${req.method} ${req.url}:`, err);
    if (!res.headersSent) {
      try { sendJson(req, res, 500, { error: 'internal server error' }); } catch { /* socket already gone */ }
    } else {
      res.destroy();
    }
  }
});

server.listen(PORT, () => {
  const bound = server.address()?.port ?? PORT; // PORT 0 = OS-picked ephemeral port
  console.log(`FictionPad server running:`);
  const served = appFile();
  console.log(`  app:     http://localhost:${bound}/ (serving ${served})`);
  if (served === 'fictionpad.html')
    console.warn('  note:    no compiled artifact yet — the dev build being served loads React/htm/marked from esm.sh at runtime.');
  console.log(`  proxy:   http://localhost:${bound}/proxy/<real-endpoint>`);
  console.log(`  storage: SQLite kv at ${DB_PATH}`);
  if (BASIC_HEADER) console.log(`  auth:    basic (user ${BASIC_USER}) — FICTIONPAD_AUTH, whole server except /health`);
  if (TOKEN) console.log(`  auth:    FICTIONPAD_TOKEN required for storage + proxy routes`);
  if (PROXY_ALLOW.length) console.log(`  proxy:   target allowlist: ${PROXY_ALLOW.join(', ')}`);
  if (!BASIC_HEADER && !TOKEN)
    console.warn('  WARNING: no auth configured — anyone who can reach this port can use storage;' +
      ' /proxy is restricted to loopback targets. Set FICTIONPAD_AUTH=user:password before exposing this server.');
  autobuildCompiled();
});
