#!/usr/bin/env node
// FictionPad local server: serves fictionpad.html, proxies LLM API calls
// (mikupad-style /proxy/*), and optionally stores sessions in SQLite.
// Zero dependencies — requires Node.js >= 22.13 (node:sqlite, unflagged).
//
// Usage:
//   node server.mjs [port]          (default port 8788)
//   open http://localhost:8788
// Then set the in-app endpoint to your real LLM server as usual — but route it
// through the proxy:  http://localhost:8788/proxy/<your-real-endpoint>
// Example:  http://localhost:8788/proxy/http://127.0.0.1:8080
//           http://localhost:8788/proxy/https://api.openai.com
// (The app normalizes and appends /v1/chat/completions etc. — everything after
// /proxy/ is forwarded verbatim as the target URL.)
//
// Env:
//   FICTIONPAD_DB       SQLite path (default: fictionpad.db next to server.mjs)
//   FICTIONPAD_TOKEN    storage routes require Authorization: Bearer <token>
//   FICTIONPAD_AUTH     user:password — whole-server HTTP Basic auth (except
//                       /health). The proxy never forwards these creds upstream;
//                       the app sends its LLM key as X-Real-Authorization instead.
//   FICTIONPAD_PROXY_ALLOW  comma-separated target host allowlist for /proxy
//                       (e.g. "proxy.example.com,10.0.0.6"). Default: any host.
// Proxy access policy:
//   - FICTIONPAD_AUTH set   → /proxy is behind Basic like everything else.
//   - only FICTIONPAD_TOKEN → /proxy requires the same Bearer token.
//   - neither set           → /proxy only forwards to loopback targets
//                             (localhost/127.0.0.1/[::1]), so an exposed
//                             unauthenticated server is not an open relay.
// 401s generated by THIS server carry `X-FictionPad-Auth: required` so the app
// can tell them apart from upstream (proxied) 401s, which pass through untagged.
//
//   FICTIONPAD_CHECKPOINT_MS  interval for PRAGMA wal_checkpoint(TRUNCATE)
//                       in ms (default 60000) — keeps the on-disk .db a
//                       recent complete snapshot even without a shutdown.
//   GET /backup       checkpoints the WAL, then streams the SQLite file as
//                     an attachment (same auth as the storage routes).
// CORS: Access-Control-Allow-Origin and the preflight answer are emitted
//   only when the request's Origin header is absent (same-origin/curl) or
//   exactly "null" (the file:// build — the only reason CORS exists). Any
//   other Origin is still served but gets no ACAO header, so browsers refuse
//   to let that page read the response (a no-auth deployment would otherwise
//   let any website drive the victim's browser through /proxy).
// Shutdown: SIGINT/SIGTERM close the db — closing the last WAL connection
//   checkpoints it and removes the -wal/-shm sidecars — then exit 0.

import http from 'node:http';
import crypto from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { existsSync, statSync, createReadStream } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { gzipSync, gunzipSync } from 'node:zlib';

const PORT = Number(process.argv[2]) || 8788;
const ROOT = dirname(fileURLToPath(import.meta.url));
const DB_PATH = process.env.FICTIONPAD_DB || join(ROOT, 'fictionpad.db');
const TOKEN = process.env.FICTIONPAD_TOKEN || null; // when set, storage routes need Bearer auth
const MAX_BODY = 8 * 1024 * 1024; // request-body cap for storage + proxy routes
const UPSTREAM_TIMEOUT_MS = 5 * 60_000; // LLM streams can be long; 5 min ceiling

// Whole-server HTTP Basic auth (LAN exposure): FICTIONPAD_AUTH=user:password.
// Everything except /health requires it; checked before the Bearer token.
let BASIC_USER = null, BASIC_HEADER = null;
if (process.env.FICTIONPAD_AUTH) {
  const i = process.env.FICTIONPAD_AUTH.indexOf(':');
  if (i > 0) {
    BASIC_USER = process.env.FICTIONPAD_AUTH.slice(0, i);
    BASIC_HEADER = `Basic ${Buffer.from(process.env.FICTIONPAD_AUTH, 'utf8').toString('base64')}`;
  } else {
    console.warn('FICTIONPAD_AUTH is malformed (expected user:password) — ignoring it.');
  }
}
// Constant-time credential comparison (length guard first — timingSafeEqual
// throws on length mismatch).
const safeEqual = (a, b) => {
  const ba = Buffer.from(String(a), 'utf8'), bb = Buffer.from(String(b), 'utf8');
  return ba.length === bb.length && crypto.timingSafeEqual(ba, bb);
};
const bearerOk = (req) => !!TOKEN && safeEqual(req.headers.authorization ?? '', `Bearer ${TOKEN}`);
const basicOk = (req) => !!BASIC_HEADER && safeEqual(req.headers.authorization ?? '', BASIC_HEADER);
// One credential check for every gated route: Basic (when configured) OR
// Bearer (when configured) — a request carries only one Authorization header,
// and app subrequests legitimately use Bearer while the browser uses Basic.
// With neither configured the server is open (local dev; see the startup warning).
const credsOk = (req) => (!BASIC_HEADER && !TOKEN) || basicOk(req) || bearerOk(req);
const isBearer = (req) => /^Bearer /i.test(req.headers.authorization ?? '');
const basicChallenge = (res, req) => {
  // A request that already presented Bearer creds comes from an API client
  // (never a bare browser navigation) — answering with WWW-Authenticate would
  // make Safari/Chrome pop the native password sheet on every failed fetch.
  // X-FictionPad-Auth tags this as OUR 401 (vs. an upstream passthrough).
  const headers = { 'Content-Type': 'application/json', 'X-FictionPad-Auth': 'required' };
  if (!isBearer(req)) headers['WWW-Authenticate'] = 'Basic realm="fictionpad"';
  res.writeHead(401, headers);
  res.end(JSON.stringify({ error: 'unauthorized' }));
};

// ---- server-side storage (mikupad-style): one kv table, gzip-compressed JSON ----
const KNOWN_STORES = new Set(['Scenarios', 'Personas', 'Chats', 'Meta', 'Characters']);
let db;
try {
  db = new DatabaseSync(DB_PATH);
  db.exec('PRAGMA journal_mode=WAL;');
  db.exec('PRAGMA busy_timeout=5000;');
  db.exec('CREATE TABLE IF NOT EXISTS kv (store TEXT, key TEXT, data BLOB, PRIMARY KEY (store, key))');
} catch (err) {
  console.error(`FictionPad: cannot open or initialize the SQLite database at ${DB_PATH}`);
  console.error(`  (${err?.message || err})`);
  console.error(`  Delete or restore ${DB_PATH}, then restart the server.`);
  process.exit(1);
}

// ---- WAL durability ----
// WAL mode keeps recent writes in fictionpad.db-wal until a checkpoint runs —
// copying just the .db (e.g. into a deploy) would silently lose them. Two
// guards: a periodic TRUNCATE checkpoint so the on-disk .db is always a
// recent complete snapshot, and a clean db.close() on shutdown — closing the
// last WAL connection checkpoints and removes the -wal/-shm sidecars.
const CHECKPOINT_MS = Number(process.env.FICTIONPAD_CHECKPOINT_MS) || 60_000;
const checkpointTimer = setInterval(() => {
  try { db.exec('PRAGMA wal_checkpoint(TRUNCATE);'); }
  catch (err) { console.warn(`WAL checkpoint failed: ${err?.message || err}`); }
}, CHECKPOINT_MS);
checkpointTimer.unref(); // housekeeping must never hold the process open
let shuttingDown = false;
const shutdown = (sig) => {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log(`FictionPad: ${sig} received — checkpointing and closing the database.`);
  clearInterval(checkpointTimer);
  try { db.close(); } catch { /* already closed */ }
  process.exit(0);
};
process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

// CORS exists solely for the file:// build, whose Origin header is the
// literal string "null". Same-origin pages and curl send no Origin and need
// nothing. Any OTHER Origin is served normally but gets no
// Access-Control-Allow-Origin header — the browser then refuses to let that
// page read the response, so a random website can't drive a visitor's
// browser through /proxy or the storage routes on a no-auth deployment.
const acaoFor = (req) => {
  const origin = req.headers.origin;
  return (origin === undefined || origin === 'null')
    ? { 'Access-Control-Allow-Origin': '*' }
    : {};
};
const sendJson = (req, res, status, obj) => {
  const headers = { 'Content-Type': 'application/json', ...acaoFor(req) };
  // Tag OUR auth failures so the app can distinguish them from upstream 401s
  // that pass through the proxy untagged.
  if (status === 401) headers['X-FictionPad-Auth'] = 'required';
  res.writeHead(status, headers);
  res.end(JSON.stringify(obj));
};
const readJsonBody = async (req) => {
  const chunks = [];
  let size = 0;
  for await (const c of req) {
    size += c.length;
    if (size > MAX_BODY) {
      const err = new Error('body too large');
      err.status = 413;
      throw err;
    }
    chunks.push(c);
  }
  return chunks.length ? JSON.parse(Buffer.concat(chunks).toString('utf8')) : {};
};

const HOP_BY_HOP = new Set([
  'host', 'connection', 'keep-alive', 'transfer-encoding', 'te',
  'trailer', 'upgrade', 'proxy-authorization', 'proxy-authenticate',
]);

// /proxy target policy (see header comment). An allowlist always wins; an
// unauthenticated server is limited to loopback targets so it cannot be
// abused as an open relay.
const PROXY_ALLOW = (process.env.FICTIONPAD_PROXY_ALLOW ?? '')
  .split(',').map(s => s.trim().toLowerCase()).filter(Boolean);
const LOOPBACK_HOSTS = new Set(['localhost', '127.0.0.1', '::1', '[::1]']);
function proxyTargetAllowed(target) {
  let host;
  try { host = new URL(target).hostname.toLowerCase(); }
  catch { return { ok: false, reason: 'unparseable proxy target' }; }
  if (PROXY_ALLOW.length) {
    return PROXY_ALLOW.includes(host)
      ? { ok: true }
      : { ok: false, reason: `proxy target host "${host}" is not in FICTIONPAD_PROXY_ALLOW` };
  }
  if (!BASIC_HEADER && !TOKEN && !LOOPBACK_HOSTS.has(host)) {
    return { ok: false, reason: `proxy only forwards to loopback targets while the server has no auth ` +
      `(set FICTIONPAD_AUTH or FICTIONPAD_TOKEN, or allow hosts via FICTIONPAD_PROXY_ALLOW)` };
  }
  return { ok: true };
}

// Serve the compiled (vendored, offline-capable) build when present — that's
// the distribution artifact; the readable source is the fallback (dev).
// Resolved per request so a rebuild is picked up without a server restart.
const appFile = () => existsSync(join(ROOT, 'fictionpad.compiled.html'))
  ? 'fictionpad.compiled.html'
  : 'fictionpad.html';

async function handleRequest(req, res) {
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);

  // CORS preflight — answered with full CORS headers only for the origins we
  // allow (see acaoFor); any other Origin gets a bare 204, which the browser
  // treats as a failed preflight.
  if (req.method === 'OPTIONS') {
    const acao = acaoFor(req);
    res.writeHead(204, 'Access-Control-Allow-Origin' in acao ? {
      ...acao,
      'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Real-Authorization',
      'Access-Control-Max-Age': '86400',
    } : {});
    return res.end();
  }

  if (url.pathname === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ ok: true }));
  }

  // Whole-server Basic auth (when FICTIONPAD_AUTH is set) — before everything
  // else. A valid Bearer token also passes (app subrequests use Bearer while
  // the browser uses Basic). /health stays open.
  if (BASIC_HEADER && !credsOk(req)) return basicChallenge(res, req);

  if (url.pathname === '/' || url.pathname === '/fictionpad.html') {
    const file = appFile();
    try {
      const html = await readFile(join(ROOT, file));
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-cache' });
      return res.end(html);
    } catch {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      return res.end(`${file} not found next to server.mjs`);
    }
  }

  // ---- storage protocol ----
  // Gated by either configured credential (Basic or Bearer); open when neither
  // is set (local dev default — see the startup warning).
  if (url.pathname === '/version' && req.method === 'GET') {
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    return sendJson(req, res, 200, { version: 1, storage: true });
  }

  // Full-db backup: checkpoint the WAL first so the streamed .db is a
  // complete snapshot, then send the raw file. Same auth as storage routes.
  if (url.pathname === '/backup') {
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    if (req.method !== 'GET') return sendJson(req, res, 405, { error: 'GET required' });
    try {
      db.exec('PRAGMA wal_checkpoint(TRUNCATE);');
      const { size } = statSync(DB_PATH);
      const stamp = new Date().toISOString().replace(/[:.]/g, '-');
      res.writeHead(200, {
        'Content-Type': 'application/octet-stream',
        'Content-Disposition': `attachment; filename="fictionpad-backup-${stamp}.db"`,
        'Content-Length': size,
        ...acaoFor(req),
      });
      createReadStream(DB_PATH).pipe(res);
    } catch (err) {
      return sendJson(req, res, 500, { error: `backup failed: ${err?.message || err}` });
    }
    return;
  }

  if (['/load', '/save', '/all', '/delete', '/list'].includes(url.pathname)) {
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    if (req.method !== 'POST') return sendJson(req, res, 405, { error: 'POST required' });
    let body;
    try { body = await readJsonBody(req); }
    catch (err) {
      if (err?.status === 413) return sendJson(req, res, 413, { error: 'body too large' });
      return sendJson(req, res, 400, { error: 'invalid JSON' });
    }
    const { store, key, data } = body ?? {};
    if (url.pathname !== '/list' && !KNOWN_STORES.has(store))
      return sendJson(req, res, 400, { error: `unknown store: ${store}` });
    switch (url.pathname) {
      case '/load': {
        const row = db.prepare('SELECT data FROM kv WHERE store = ? AND key = ?').get(store, String(key));
        if (!row) return sendJson(req, res, 404, { error: 'not found' });
        try {
          return sendJson(req, res, 200, { data: JSON.parse(gunzipSync(row.data).toString('utf8')) });
        } catch (err) {
          console.warn(`corrupted kv row ${store}/${key}: ${err?.message || err}`);
          return sendJson(req, res, 500, { error: 'corrupted stored data' });
        }
      }
      case '/save': {
        if (key == null || String(key) === '') return sendJson(req, res, 400, { error: 'missing key' });
        if (data === undefined) return sendJson(req, res, 400, { error: 'missing data' });
        const blob = gzipSync(Buffer.from(JSON.stringify(data), 'utf8'));
        db.prepare('INSERT OR REPLACE INTO kv (store, key, data) VALUES (?, ?, ?)').run(store, String(key), blob);
        return sendJson(req, res, 200, { ok: true });
      }
      case '/all': {
        const entries = {};
        for (const row of db.prepare('SELECT key, data FROM kv WHERE store = ?').all(store)) {
          try {
            entries[row.key] = JSON.parse(gunzipSync(row.data).toString('utf8'));
          } catch (err) {
            // One bad row must not take down the whole store (the app calls
            // /all at boot) — skip it and keep serving the rest.
            console.warn(`skipping corrupted kv row ${store}/${row.key}: ${err?.message || err}`);
          }
        }
        return sendJson(req, res, 200, { entries });
      }
      case '/delete': {
        db.prepare('DELETE FROM kv WHERE store = ? AND key = ?').run(store, String(key));
        return sendJson(req, res, 200, { ok: true });
      }
      case '/list': {
        const stores = {};
        for (const row of db.prepare('SELECT store, COUNT(*) AS n FROM kv GROUP BY store').all())
          stores[row.store] = row.n;
        return sendJson(req, res, 200, { stores });
      }
    }
  }

  if (url.pathname.startsWith('/proxy/')) {
    // Gated by either configured credential, same as the storage routes; open
    // only when the server has no auth at all (and then loopback-only below).
    if (!credsOk(req)) return sendJson(req, res, 401, { error: 'unauthorized' });
    let target;
    try {
      target = decodeURIComponent(url.pathname.slice('/proxy/'.length)) + url.search;
    } catch {
      return sendJson(req, res, 400, { error: 'malformed proxy target (bad percent-encoding)' });
    }
    if (!/^https?:\/\//i.test(target)) {
      res.writeHead(400, { 'Content-Type': 'text/plain', ...acaoFor(req) });
      return res.end('proxy target must start with http:// or https://');
    }
    const verdict = proxyTargetAllowed(target);
    if (!verdict.ok) {
      res.writeHead(403, { 'Content-Type': 'text/plain', ...acaoFor(req) });
      return res.end(verdict.reason);
    }

    // Collect the request body (if any), capped at MAX_BODY.
    const chunks = [];
    let size = 0, tooBig = false;
    for await (const chunk of req) {
      size += chunk.length;
      if (size > MAX_BODY) { tooBig = true; break; }
      chunks.push(chunk);
    }
    if (tooBig) {
      req.destroy();
      return sendJson(req, res, 413, { error: 'body too large' });
    }
    const body = chunks.length ? Buffer.concat(chunks) : undefined;

    const headers = {};
    for (const [k, v] of Object.entries(req.headers)) {
      const lk = k.toLowerCase();
      if (HOP_BY_HOP.has(lk) || lk === 'cookie' || lk === 'x-real-authorization') continue;
      if (lk === 'authorization' && BASIC_HEADER && safeEqual(v, BASIC_HEADER)) continue; // never leak our own Basic creds upstream
      if (lk === 'authorization' && TOKEN && safeEqual(v, `Bearer ${TOKEN}`)) continue;   // ...nor our own Bearer token
      if (typeof v === 'string') headers[k] = v;
    }
    // The app sends the LLM key as X-Real-Authorization when routing through
    // this proxy; map it to the upstream Authorization header.
    const realAuth = req.headers['x-real-authorization'];
    if (typeof realAuth === 'string') headers['authorization'] = realAuth;

    // Propagate client disconnects to the upstream request; cap the upstream
    // call at UPSTREAM_TIMEOUT_MS so a hung endpoint can't pin a socket forever.
    const ac = new AbortController();
    res.on('close', () => ac.abort());
    const signal = AbortSignal.any([ac.signal, AbortSignal.timeout(UPSTREAM_TIMEOUT_MS)]);

    try {
      const upstream = await fetch(target, {
        method: req.method,
        headers,
        body,
        redirect: 'manual', // never follow redirects past the target policy — a 3xx passes through to the client
        signal,
      });

      const resHeaders = {
        ...acaoFor(req),
        'Content-Type': upstream.headers.get('content-type') || 'application/octet-stream',
        'Cache-Control': 'no-cache',
      };
      res.writeHead(upstream.status, resHeaders);

      // Stream the body back chunk-by-chunk (keeps SSE/token streaming live).
      if (!upstream.body) return res.end();
      const reader = upstream.body.getReader();
      const pump = async () => {
        try {
          for (;;) {
            const { done, value } = await reader.read();
            if (done) break;
            if (!res.write(value)) {
              await new Promise((resolve) => res.once('drain', resolve));
            }
          }
          res.end();
        } catch {
          res.destroy();
        }
      };
      pump();
    } catch (err) {
      if (err?.name === 'AbortError') return;
      res.writeHead(502, { 'Content-Type': 'text/plain', ...acaoFor(req) });
      res.end(`proxy error: ${err?.message || err}`);
    }
    return;
  }

  res.writeHead(404, { 'Content-Type': 'text/plain' });
  res.end('not found');
}

// The handler is async — an uncaught throw would kill the process. Last-line
// safety net: answer 500 and keep serving.
const server = http.createServer(async (req, res) => {
  try {
    await handleRequest(req, res);
  } catch (err) {
    console.error(`unhandled error on ${req.method} ${req.url}:`, err);
    if (!res.headersSent) {
      try { sendJson(req, res, 500, { error: 'internal server error' }); } catch { /* socket already gone */ }
    } else {
      res.destroy();
    }
  }
});

server.listen(PORT, () => {
  console.log(`FictionPad server running:`);
  console.log(`  app:     http://localhost:${PORT}/ (serving ${appFile()})`);
  console.log(`  proxy:   http://localhost:${PORT}/proxy/<real-endpoint>`);
  console.log(`  storage: SQLite kv at ${DB_PATH}`);
  if (BASIC_HEADER) console.log(`  auth:    basic (user ${BASIC_USER}) — FICTIONPAD_AUTH, whole server except /health`);
  if (TOKEN) console.log(`  auth:    FICTIONPAD_TOKEN required for storage + proxy routes`);
  if (PROXY_ALLOW.length) console.log(`  proxy:   target allowlist: ${PROXY_ALLOW.join(', ')}`);
  if (!BASIC_HEADER && !TOKEN)
    console.warn('  WARNING: no auth configured — anyone who can reach this port can use storage;' +
      ' /proxy is restricted to loopback targets. Set FICTIONPAD_AUTH=user:password before exposing this server.');
});
